FROM node:21-alpine

# See the .dockerignore for details

COPY public /home/app/public
COPY src /home/app/src
COPY public /home/app/public
COPY .env.prod /home/app/.env
COPY index.html /home/app/index.html
COPY package.json /home/app/package.json
COPY tsconfig.json /home/app/tsconfig.json
COPY tsconfig.node.json /home/app/tsconfig.node.json
COPY vite.config.ts /home/app/vite.config.ts

WORKDIR /home/app
RUN npm install
RUN npm run build
