services:
  psql:
    container_name: postgres-trainingportal2-dev
    image: postgres
    environment:
      POSTGRES_DB: trainingportal2db
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      PGDATA: /data/postgres
    volumes:
      - db2:/data/postgres
    ports:
      - "56321:5432"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db2: