package net.dnadas.training_portal.model.auth;

public enum PermissionType {
  GROUP_ADMIN, GROUP_EDITOR, GROUP_MEMBER,
  PROJECT_ADMIN, PROJECT_EDITOR, PROJECT_ASSIGNED_MEMBER, PROJECT_COORDINATOR,
  TASK_ASSIGNED_MEMBER
}