spring:
  profiles:
    default: dev

  datasource:
    hikari:
      maximum-pool-size: 250
      minimum-idle: 5
      idle-timeout: 500000
      max-lifetime: 600000
      connection-timeout: 30000

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    web-application-type: servlet
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 3MB
