server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  datasource:
    url: jdbc:postgresql://localhost:56321/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update

logging:
  level:
    root: warn
    net.dnadas: info
    #org.springframework: trace
    #org.hibernate.sql: trace
