export enum PermissionType {
  GROUP_ADMIN = "GROUP_ADMIN",
  GROUP_EDITOR = "GROUP_EDITOR",
  GROUP_MEMBER = "GROUP_MEMBER",
  PROJECT_ADMIN = "PROJECT_ADMIN",
  PROJECT_COORDINATOR = "PROJECT_COORDINATOR",
  PROJECT_EDITOR = "PROJECT_EDITOR",
  PROJECT_ASSIGNED_MEMBER = "PROJECT_ASSIGNED_MEMBER",
  TASK_ASSIGNED_MEMBER = "TASK_ASSIGNED_MEMBER"
}
